version: '3'
services:
  development:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "npm install && ng serve --host 0.0.0.0"
    volumes:
         - .:/app
         - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 4201:4200
      - 5100:5100
      - 9005:9005
      - 8080:8080
